### ISSUE TITLE
List of references in module description

### ISSUE THREAD

**Issue by pbloem** [Data2Semantics/d2s-tools#6]
Currently providing a set of references as an input in the workflow description is not supported (only raw values). 

We should even be able to create a mixed list, with some raw values, and some references. This will be tricky.

**Comment by pbloem** [comment]
We decided that this should be implemented as a list of associative arrays in yaml

```
- module:
    name: MyModule
    source: ...
    inputs:
      dataset:
         - reference: csvloader.result
         - reference: htmlloader.result
         - reference: randomgenerator.result
         - raw: [0.1, 0.2, 0.3]
```

If a list contains only raw values, the reference/raw keys can be omitted. 

In the implementation, the parse should make sure to mark in the module that it is dependent on the referenced modules, since this will affect its rank. During instantiation the ModuleInstance can be created with a single ReferenceInput.

We will either need to adap MultiInput, or create an additional MixedMultiInput...
