### ISSUE TITLE
Module shorthand

### ISSUE THREAD

**Issue by pbloem** [Data2Semantics/d2s-tools#9]
For quick modules, with a single output, it would be nice to be able to use a shorthand. Something like the following:

``` yaml
module:
  name: big complex module
  inputs:
    dataset: smooth(csv('C:\data\dataset.csv), 0.3)
```

Which would be equivalent to 

``` yaml
- module:
    name: csv
    inputs:
      file: 'C:\data\data.csv'

- module:
    name: smooth
    inputs:
      data: csv.result
      smoothing factor: 0.3

- module:
    name: big complex module
    inputs:
      dataset: smooth.result
```

This should be thought out carefully on the design level before implementation.

**Comment by pbloem** [comment]
Maybe like this...

``` yaml
module:
  name: big complex module
  inputs:
    dataset: !inline
       smooth: 
          data: !inline
             csv: 
               file:'C:\data\dataset.csv' 
          smoothing factor: 0.3
```

It's a little more verbose, but it'll be easier to parse, I think.
